version: '3.8'

services:
  nodejs:
    image: your-nodejs-image
    ports:
      - "8888:8888"
    networks:
      - my-network

  nginx:
    image: your-nginx-image
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
