version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
