# Stage 2: Create a lightweight image with Nginx and copy configuration
FROM nginx

COPY ./default.conf /etc/nginx/conf.d/

# Expose port 80 from the Nginx stage (optional, depends on your requirements)
EXPOSE 80

# Set the entry point to start Nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
