version: '3.8'

services:
  localhost:
    build: .
    container_name: nodejsserver
    hostname: nodejsserver
    ports:
      - "8888:8888"
    networks:
      - example-net

  nginx:
    build: .
    container_name: nginx
    hostname: nginx
    ports:
      - "2023:80"
    depends_on:
      - localhost
    networks:
      - example-net

networks:
  example-net:
    external: true
